---
title: "merge drought severity and the master dataset"
author: "Daniel Malone"
date: "2023-11-10"
output: html_document
---
Set-up chunk
```{r}
library(tidyverse)
```

```{r}
#merge the master data and the drought severity data
drought_clean2 = drought_clean1|>
  arrange(fips)
droughtandmaster = merge(master_data, drought_clean2)
#create a varible with dummy variables for each category of drought and last year precipitation
droughtandmaster = droughtandmaster|>
  mutate(cat4dummy = cat_4 > 0)|>
  mutate(droughtseverity = ifelse(cat_4 > 0, 5,
                                  ifelse(cat_3 > 0, 4,
                                         ifelse(cat_2 > 0, 3,
                                                ifelse(cat_1 > 0, 2,
                                                       ifelse(cat_0 > 0, 1, 0))))))|>
  mutate(lastyearprecip = lag(precip))|>
  #removes observations with no last year drought
  filter(is.na(lastyearprecip) == FALSE)
#turns droughtseverity into a factor to function as a dummy variable
droughtandmaster$droughtseverity = factor(droughtandmaster$droughtseverity)
droughtandmaster = droughtandmaster|>
  mutate(fipscopy = fips)|>
  separate_wider_position(fipscopy, c(statefip = 2, countyfip = 3))
droughtandmaster$statefip = as.numeric(droughtandmaster$statefip)
```

```{r}
#runs the regression.  this may take a very long time
#this regression is using county fixed effects.  I do not recommend using county fixed effects, as it creates an unworkable regression output
ols = lm(droughtandmaster$net_migration ~ droughtandmaster$droughtseverity + droughtandmaster$lastyearprecip * droughtandmaster$droughtseverity + droughtandmaster$fips + droughtandmaster$year)
summary(ols)
#this one is the same, but using state fixed effects instead of county
ols2 = lm(droughtandmaster$net_migration ~ droughtandmaster$droughtseverity + droughtandmaster$lastyearprecip * droughtandmaster$droughtseverity + droughtandmaster$state + droughtandmaster$year)
summary(ols2)
```

```{r}
setwd("C:/Users/malon/OneDrive/Documents/GitHub/econometrics-project-B/Econometrics Project/Data")
save(droughtandmaster,file = "droughtandmaster.Rda")
write_csv(droughtandmaster, file = "droughtandmaster.csv")
#this one is unusable;  it cannot be saved to onedrive or pushed to github
#save(ols, file = "olswithfips.Rda")
save(ols2, file = "olswithstate.Rda")
```